<?php

/**
 * Implements hook_menu(). 
 */

function generate_nodes_menu() {

    $items = array();

    $items['events/generated-list'] = array(
        'page callback' => 'generate_nodes_generate',
        'title' => 'Generate Nodes',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access content'),
    );

    return $items;
}


function generate_nodes_node_view($node, $view_mode, $langcode) {
    //dpm($node);
}

function generate_random_title() {
    $words = ['football','cars','soccer','charity','pets','africa','europe','belgium','romania','france'];
    $words_len = count($words);
    return $words[rand(0,$words_len - 1)] . ' ' . rand(0,10000) . ' ' . $words[rand(0,$words_len - 1)];
}


function generate_random_date() {
    $int = mt_rand(1485820800, 3789504000);
    $string = date('Y-m-d',$int);
    return $string;
}

function generate_random_location() {
    $locations = ['Bacau','Iasi','Bucuresti','Cluj','Timisoara','Londra','Paris','Berlin','Lisabona','Budapesta','Tokyo','Brasov','New York'];
    $locations_len = count($locations);

    return $locations[mt_rand(0,$locations_len - 1)];
}

function generate_link_to_nodes($path) {
    global $base_url;
    global $base_path;
    $link = $base_url . $base_path . $path;
    return $link;
}

function generate_random_participants() {
    $participants = ['Ion','Gigel','Vasile','Cosmin','Marina','Emilia','Tudor','Alexandru','Florin'];
    $arr_of_people = array();
    $rand_num = mt_rand(1,3);
    for($i = 0 ; $i < $rand_num ; $i++){
        $arr_of_people[] = $participants[mt_rand(0,count($participants)-1)];
    }

    return implode(', ',$arr_of_people);
}

function generate_nodes_generate() {
    $content_type = 'event';
    $message = '';
    for($i = 0 ; $i < 10; $i++){
        $node = new stdClass();

        $node->type = $content_type;

        $node->title = generate_random_title();

        //node_object_prepare($node);
        
        $rand_participants = generate_random_participants();
        $node->event_participants['und'][0]['value'] = $rand_participants;
        $node->event_participants['und'][0]['safe_value'] = $rand_participants;
        $node->language = LANGUAGE_NONE;
        $random_date = generate_random_date();
        $node->event_date['und'][0]['value'] = $random_date;
        $node->event_date['und'][0]['safe_value'] = $random_date;
        $node->event_location['und'][0]['value'] = generate_random_location();
        $node->uid = 1;
        if($node = node_submit($node)){

            node_save($node);

            $message = '<p>' . t('Your nodes have been created successfuly!') . '</p>';
            $message .= '<p>' . t('You can view your nodes at the following ');
            $message .= '<a href="' . generate_link_to_nodes('events/list') . '">' . t('address') . '</a> ';
            $message .= 'or you can create new content again by clicking <a href="' . generate_link_to_nodes('events/generated-list');
            $message .= '">here</a>.</p>';
        } else{
            $message = t('An error occured and processing did not complete.');
        }
        
    }
    return $message;
}